name: tests-payments

# on:
#   pull_request:
#     paths:
#       - 'payments/**'
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd payments && npm install && npm run test:ci
